const BlogData = [
    {
        id:1,
        date:"January 01, 2020",
        categeory: "Business",
        title: "The Most Advance Business Plan",
        cover : "/images/singlepage/blog-1.jpg",
        para:" simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
        desc: " simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
        id:2,
        date:"January 01, 2021",
        categeory: "Travelling",
        title: "Beautiful Home Page",
        cover : "/images/singlepage/blog-2.jpg",
        para:" simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
        desc: " simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
        id:3,
        date:"January 22, 2022",
        categeory: "Development",
        title: "The Most Advance Business Plan",
        cover : "/images/singlepage/blog-3.jpg",
        para:" simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
        desc: " simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
        id:4,
        date:"January 23, 2023",
        categeory: "Motion Designer",
        title: "The Most Advance Business Plan",
        cover : "/images/singlepage/blog-4.jpg",
        para:" simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
        desc: " simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
        id:5,
        date:"January 01, 2000",
        categeory: "Content Writing",
        title: "The Most Advance Business Plan",
        cover : "/images/singlepage/blog-5.jpg",
        para:" simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
        desc: " simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
        id:6,
        date:"January 11, 2021",
        categeory: "Web Development",
        title: "The Most Advance Business Plan",
        cover : "/images/singlepage/blog-6.jpg",
        para:" simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
        desc: " simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
        id:7,
        date:"January 01, 2020",
        categeory: "Business Strategy",
        title: "The Most Advance Business Plan",
        cover : "/images/singlepage/blog-1.jpg",
        para:" simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
        desc: " simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
        id:8,
        date:"January 01, 2023",
        categeory: "Motion Designer",
        title: "The Most Advance Business Plan",
        cover : "/images/singlepage/blog-2.jpg",
        para:" simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
        desc: " simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
        id:9,
        date:"January 01, 2023",
        categeory: "Business",
        title: "The Most Advance Business Plan",
        cover : "/images/singlepage/blog-6.jpg",
        para:" simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
        desc: " simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },

]
export default BlogData;